Feature/create activity program#8
matopenKW/waseda_covit19_docs_backend pull request #16
Opened 2021-01-25 14:13 UTC by oshikun

sqlと構造体のファイルを作成したのでレビューをお願いします。

2021-01-25 14:27 UTC, matopenKW requested changes
また、user単位での入力になるためuser_idを追加してください。

2021-01-25 14:31 UTC, matopenKW requested changes

2021-01-25 14:31 UTC, matopenKW commented on local/db/activity_program.sql
> +create table activity_program (
gormの仕様上
DB名は構造体の複数形という形にしてください。

```suggestion
create table activity_programs (
```

2021-01-25 14:31 UTC, matopenKW commented on local/db/activity_program.sql
> +  datetime           timestamp primary key,
idがインクリメントされるので、datetimeのPKは不要かと

```suggestion
  datetime,
```

2021-01-25 14:31 UTC, matopenKW commented on app/model/activity_program.go
> +	ID               int
gormの仕様上、PKにはオプションを追加してください。

```suggestion
	ID               int `gorm:"primaryKey"`
```

2021-01-25 14:33 UTC, matopenKW commented
github のsuggestionという機能を使っています。

Commit suggestonというボタンを押せば、変更して欲しい部分が反映されます。

2021-01-26 00:20 UTC, matopenKW commented
@oshikun 
追加の指摘になってしまって申し訳ない。
`update_time`, `create_time`の定義もお願いします。

2021-01-26 01:14 UTC, oshikun commented
@matopenKW 
`create_id`,`update_id`の追加も必要ですか。

2021-01-28 13:44 UTC, matopenKW commented
@oshikun 
update_id、create_idは不要です。

ごめんなさい。
名称はupdate_time、create_timeで統一しようか。

2021-01-28 15:31 UTC, matopenKW requested changes

2021-01-28 15:31 UTC, matopenKW commented on local/db/activity_program.sql
> +  id                 serial primary key,
PKここで定義ではなく、一番下でまとめちゃってください。
```suggestion
  id                 serial,
```

2021-01-28 15:31 UTC, matopenKW commented on local/db/activity_program.sql
> +  update_time        timestamp,
timestampは自動で設定できる様にお願いします。
また、PKの設定はまとめちゃっていいです。
```suggestion
  create_time        timestamp default CURRENT_TIMESTAMP,
  update_time        timestamp default CURRENT_TIMESTAMP,
  CONSTRAINT routes_PK PRIMARY KEY (id)
```

2021-01-28 15:31 UTC, matopenKW commented on local/db/activity_program.sql
> +        CURRENT_TIMESTAMP
自動で設定するところなので、CURRENT_TIMESTAMPは消していいです。
```suggestion
        'contact_abstract_2'
```

2021-01-28 15:35 UTC, matopenKW commented
@oshikun 
makeファイルを新しく作りました。
そのため、SQLファイルをlocal/db/sqlに移動しました。
https://github.com/matopenKW/waseda_covit19_docs_backend/pull/16/commits/12afaa105df65de9a5b0c870e0b6e2ff4ca87067

SQLの実行はプロジェクト直下で
`$ make execute-sql sqlname=<sqlファイル名>`として実行してみてください。

2021-01-28 15:35 UTC, matopenKW approved these changes

2021-01-28 15:53 UTC, merged